// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-opportunity/internal/sdk/models/shared"
	"net/http"
)

type GetOpportunityRequest struct {
	// Hydrates entities in relations when passed true
	Hydrate *bool `queryParam:"style=form,explode=true,name=hydrate"`
	// Opportunity ID
	OpportunityID string `pathParam:"style=simple,explode=false,name=opportunityId"`
}

func (o *GetOpportunityRequest) GetHydrate() *bool {
	if o == nil {
		return nil
	}
	return o.Hydrate
}

func (o *GetOpportunityRequest) GetOpportunityID() string {
	if o == nil {
		return ""
	}
	return o.OpportunityID
}

type GetOpportunityResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Opportunity response
	Opportunity *shared.Opportunity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *GetOpportunityResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *GetOpportunityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetOpportunityResponse) GetOpportunity() *shared.Opportunity {
	if o == nil {
		return nil
	}
	return o.Opportunity
}

func (o *GetOpportunityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetOpportunityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetOpportunityResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
