// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-opportunity/internal/sdk/models/shared"
	"net/http"
)

type PatchOpportunityRequest struct {
	// Opportunity patch request
	OpportunityPatch shared.OpportunityPatch `request:"mediaType=application/json"`
	// Opportunity ID
	OpportunityID string `pathParam:"style=simple,explode=false,name=opportunityId"`
}

func (o *PatchOpportunityRequest) GetOpportunityPatch() shared.OpportunityPatch {
	if o == nil {
		return shared.OpportunityPatch{}
	}
	return o.OpportunityPatch
}

func (o *PatchOpportunityRequest) GetOpportunityID() string {
	if o == nil {
		return ""
	}
	return o.OpportunityID
}

type PatchOpportunityResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Opportunity response
	Opportunity *shared.Opportunity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *PatchOpportunityResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *PatchOpportunityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchOpportunityResponse) GetOpportunity() *shared.Opportunity {
	if o == nil {
		return nil
	}
	return o.Opportunity
}

func (o *PatchOpportunityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchOpportunityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchOpportunityResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
