// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DollarRelationRef struct {
	ID       *string  `json:"_id,omitempty"`
	Tags     []string `json:"_tags,omitempty"`
	EntityID *string  `json:"entity_id,omitempty"`
	// the property of the entity (pointed by entity_id) to be used as the reference
	Path *string `json:"path,omitempty"`
}

func (o *DollarRelationRef) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *DollarRelationRef) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *DollarRelationRef) GetEntityID() *string {
	if o == nil {
		return nil
	}
	return o.EntityID
}

func (o *DollarRelationRef) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

type BaseRelationRef struct {
	DollarRelationRef []DollarRelationRef `json:"$relation_ref,omitempty"`
}

func (o *BaseRelationRef) GetDollarRelationRef() []DollarRelationRef {
	if o == nil {
		return nil
	}
	return o.DollarRelationRef
}
