// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-opportunity/internal/sdk/pkg/utils"
	"time"
)

type OpportunityCreateDates struct {
	Tags  []string   `json:"_tags,omitempty"`
	Dates *string    `json:"dates,omitempty"`
	Value *time.Time `json:"value,omitempty"`
}

func (o OpportunityCreateDates) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpportunityCreateDates) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OpportunityCreateDates) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *OpportunityCreateDates) GetDates() *string {
	if o == nil {
		return nil
	}
	return o.Dates
}

func (o *OpportunityCreateDates) GetValue() *time.Time {
	if o == nil {
		return nil
	}
	return o.Value
}

type OpportunityCreateSource struct {
	Href  *string `default:"null" json:"href"`
	Title *string `default:"manual" json:"title"`
}

func (o OpportunityCreateSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpportunityCreateSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OpportunityCreateSource) GetHref() *string {
	if o == nil {
		return nil
	}
	return o.Href
}

func (o *OpportunityCreateSource) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

type OpportunityCreate struct {
	Address          *BaseRelationRef         `json:"address,omitempty"`
	BillingAddress   *BaseRelationRef         `json:"billing_address,omitempty"`
	CurrentTask      *string                  `default:"open" json:"current_task"`
	Customer         *BaseRelation            `json:"customer,omitempty"`
	Dates            []OpportunityCreateDates `json:"dates,omitempty"`
	DeliveryAddress  *BaseRelationRef         `json:"delivery_address,omitempty"`
	Items            *BaseRelation            `json:"items,omitempty"`
	OpportunityTitle string                   `json:"opportunity_title"`
	Payment          *BaseRelationRef         `json:"payment,omitempty"`
	Source           *OpportunityCreateSource `json:"source,omitempty"`
	SourceType       *string                  `default:"manual" json:"source_type"`
	Status           *string                  `default:"open" json:"status"`
}

func (o OpportunityCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpportunityCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OpportunityCreate) GetAddress() *BaseRelationRef {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *OpportunityCreate) GetBillingAddress() *BaseRelationRef {
	if o == nil {
		return nil
	}
	return o.BillingAddress
}

func (o *OpportunityCreate) GetCurrentTask() *string {
	if o == nil {
		return nil
	}
	return o.CurrentTask
}

func (o *OpportunityCreate) GetCustomer() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.Customer
}

func (o *OpportunityCreate) GetDates() []OpportunityCreateDates {
	if o == nil {
		return nil
	}
	return o.Dates
}

func (o *OpportunityCreate) GetDeliveryAddress() *BaseRelationRef {
	if o == nil {
		return nil
	}
	return o.DeliveryAddress
}

func (o *OpportunityCreate) GetItems() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *OpportunityCreate) GetOpportunityTitle() string {
	if o == nil {
		return ""
	}
	return o.OpportunityTitle
}

func (o *OpportunityCreate) GetPayment() *BaseRelationRef {
	if o == nil {
		return nil
	}
	return o.Payment
}

func (o *OpportunityCreate) GetSource() *OpportunityCreateSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *OpportunityCreate) GetSourceType() *string {
	if o == nil {
		return nil
	}
	return o.SourceType
}

func (o *OpportunityCreate) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
