// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Dates struct {
	Tags  []types.String `tfsdk:"tags"`
	Dates types.String   `tfsdk:"dates"`
	Value types.String   `tfsdk:"value"`
}
